### ISSUE TITLE
Interviews - tracking issue

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/node-library-storage#6]

**Comment by reikopleau** [comment]
started interviews doc: [https://docs.google.com/document/d/1rAj1HW3HnmBVYR9ttuR3Ox3bZpHxKDmBKwRJYyut_ts/edit?usp=sharing](https://docs.google.com/document/d/1rAj1HW3HnmBVYR9ttuR3Ox3bZpHxKDmBKwRJYyut_ts/edit?usp=sharing)

Questions for archivists, curators, directors, etc. with zero to basic knowledge of blockchain = ready for review

**Comment by writerly03** [comment]
@reikopleau Added some questions in; we can chat about other angles in the meeting today

**Comment by reikopleau** [comment]
Created an interview invitation email template, link added to Notion Docs and also here:
[https://docs.google.com/document/d/1cGW9JEfH581M0qdUgwuQw-d5vBNhBlaCWddv5RFKDc8/edit?usp=sharing](https://docs.google.com/document/d/1cGW9JEfH581M0qdUgwuQw-d5vBNhBlaCWddv5RFKDc8/edit?usp=sharing)

**Comment by reikopleau** [comment]
06/18/2024 -- Anna Tidlund interview notes posted on Interview Q&A tab of project track sheet: 
[https://docs.google.com/spreadsheets/d/18pxvfOmsJyHOWBh_MbAHd0GX8w9_T-jlP81PDXCxD0M/edit?usp=sharing](https://docs.google.com/spreadsheets/d/18pxvfOmsJyHOWBh_MbAHd0GX8w9_T-jlP81PDXCxD0M/edit?usp=sharing)

**Comment by writerly03** [comment]
Closing this as Round 1 of interviews ended in August. Interview notes are here: https://docs.google.com/spreadsheets/d/18pxvfOmsJyHOWBh_MbAHd0GX8w9_T-jlP81PDXCxD0M/edit?gid=264197310#gid=264197310
